### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kmsimproject** [shaheriar/VALWATCH#4]
![image](https://user-images.githubusercontent.com/68764872/217481925-e224233b-af81-4dfb-bcd0-15e755f7287b.png)
what's problem

**Comment by cryingtothenextuniverise** [comment]
1. Delete import secretvars
ss = secretvars.secretvars() from bot.py
2. TOKEN = ss.tokenid
GUILD = ss.guild delete ss.token id and put "TOKEN" same with guild.
